### ISSUE TITLE
English tag does not seem to be working

### ISSUE THREAD

**Issue by lidi-WMDE** [wmde/wikimedia.de#6] opened 2018-06-13 07:28 UTC
Applying the "english" tag (whether in combination with the "deutsch" tag or not) to a blog post, currently won't make the blog post appear in the website's English "current" section. Test case was Jens Ohlig's recent blog post on tools around Wikidata in Wikipedia (https://blog.wikimedia.de/2018/06/01/tools-for-wikipedians-keeping-track-of-whats-going-on-on-wikidata-from-wikipedia-2/)

**Comment by JeroenDeDauw** [comment] 2018-06-13 08:09
Not an issue with the website. I was told to use the "english" tag and then explicitly asked if that is this one https://blog.wikimedia.de/tag/english/, to which the answer was yes. As you can see by following that link, Jens his post does not show there. My guess is that you used a different tag

**Comment by lidi-WMDE** [comment] 2018-06-13 09:03
I've had another look at it with Masin: the taxonomy of tags and languages is fully adapted to one tag and one language within the blog now, the problem with the website link seems to be that the website will only pull articles with the tag "english" that are also qualified as German language within the blog. For the workings of the blog, it's important though that English articles are understood by wordpress as English language blog entries (because they are linked to their German equivalent).

**Comment by JeroenDeDauw** [comment] 2018-06-13 09:24
The link I provided is the blogs own list of articles with the tag "english". If you installed some language plugin on the blog that somehow breaks that standard behavior, that is not something the website can magically fix on its end, since the unexpected behavior is on the blog.

**Comment by lidi-WMDE** [comment] 2018-06-13 09:32
more productively: We do need the plug-in so we can't go around that. Is there any way between Masin and you to look for a solution to that issue (nvm whether the technical solution lies within the blog or website code)?

**Comment by fluchtkapsel** [comment] 2018-06-13 10:55
Looking at the provided link, I see a list of articles. I can only guess the website uses some other way of retrieving the articles.

**Comment by JeroenDeDauw** [comment] 2018-06-13 14:43
The mentioned Jens article was not showing up there when I first checked today. It does now.

Thing is nothing is showing up on the website anymore. Cause: the tag the website used was renamed or removed and another tag with the same name was added. Since the wordpress API works with tag IDs and not names, this breaks API consumers such as the website. Idk why the API does not have a tag name option... quite dumb if you ask me. Anyway, if you delete the tag and switch to a new one, the site will need to be updated to match this change.

Here is the update: https://github.com/wmde/wikimedia.de/pull/7

**Comment by JeroenDeDauw** [comment] 2018-06-13 14:49
After changing to use the new tag, the Jens post still does not show. Reason: blog says access to the featured image is not allowed. "Du bist leider nicht berechtigt, diese Aktion durchzuführen."

Presumably someone forgot to publish the image or something like that?

**Comment by lidi-WMDE** [comment] 2018-06-13 14:53
Do you mean the featured image or the Beitragsbild? Usually it pulls the Beitragsbild for the website but I've added it as a featured image as well in case you want to test stuff

**Comment by JeroenDeDauw** [comment] 2018-06-13 15:05
I mean the thing called "featured_media" by the wordpress API. I have never looked at the editing interface of the blog so have no idea what names it uses for things.

**Comment by lidi-WMDE** [comment] 2018-06-28 07:38
Hi Jeroen and Masin,

Could you please have a look at the issue together as soon as possible? The English news section remains non-functional. 

Thanks!

**Comment by JeroenDeDauw** [comment] 2018-06-28 16:33
The news section is working just fine. You can see this here: https://staging.wikimedia.de/en

The production website is still running the code from before the fix I made 15 days ago.

As I mentioned several times already, I am not able to update to production site due to the permissions on the server. I'm getting a bit annoyed that the fixes I make are getting deployed very slowly and that I need to keep spending time on checking that the production website indeed has not been updated yet.

**Comment by JeroenDeDauw** [comment] 2018-06-28 16:36
This issue tracker is also intended for issues with the software, not operations concerns. Hence I will close this ticket, since the issue is not with the software. Please file an issue with IT.

**Closed as completed by JeroenDeDauw** 2018-06-28 16:36 UTC

**Comment by JeroenDeDauw** [comment] 2018-07-01 19:08
The permission issue has been resolved and I deployed the latest version of the site to production, which is now showing the English posts as expected.
